[project]
name = "travel-agency"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=5.0.0",
    "mysql-connector-python>=9.5.0",
    "pwinput>=1.0.3",
    "tabulate>=0.9.0",
]
